apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx 
  namespace: kube-system
spec:
  rules:
  - host: k8.jameselgar.com 
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx
          servicePort: 80

